id: I2CB94C60
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:09:06+00:00'
last_modified: '2022-06-08T12:50:10.306753+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18958
  title: དཔལ་དུས་ཀྱི་འཁོར་ལོའི་ཕྱི་ནང་གཞན་གསུམ་གྱི་བསྡུས་དོན་རིགས་ལྡན་དགྱེས་པའི་འཛུམ་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    456A:
      image_group_id: I8LS18960
      title: Volume 1 of dpal dus kyi 'khor lo'i phyi nang gzhan gsum gyi bsdus don
        rigs ldan dgyes pa'i 'dzum zer zhes bya ba bzhugs so/jo nang e waM shes rig
        dpe tshogs/ 12
      total_pages: 342
      order: 1
      base_file: 456A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
