id: P006948
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18958
  title: དཔལ་དུས་ཀྱི་འཁོར་ལོའི་ཕྱི་ནང་གཞན་གསུམ་གྱི་བསྡུས་དོན་རིགས་ལྡན་དགྱེས་པའི་འཛུམ་ཟེར།
  author: ''
  volumes:
    39c7d8eaff4a4dffbb91b4385769cf42:
      image_group_id: I8LS18960
      title: ''
      volume_number: 1
      total_pages: 342
ebook_metadata:
  title: དཔལ་དུས་ཀྱི་འཁོར་ལོའི་ཕྱི་ནང་གཞན་གསུམ་གྱི་བསྡུས་དོན་རིགས་ལྡན་དགྱེས་པའི་འཛུམ་ཟེར།
  author: ''
  sku: P006948
  cover: cover.jpg
  layers:
  - pagination
